namespace definitions {

  // WORKING FOLDER STRINGS
  const std::string COMMAND_WORKING_FOLDER = "KML-TOWN  --";
  const std::string CROP_COMMAND_WORKING_FOLDER = "KML-TOWN  --CROP";
  const std::string SORT_COMMAND_WORKING_FOLDER = "KML-TOWN  --SORT";
  const std::string PINS_PATH_COMMAND_WORKING_FOLDER = "KML-TOWN  --PINS-PATH";
  const std::string PINS_PATH_SEGMENTS_COMMAND_WORKING_FOLDER = "KML-TOWN  --PINS-PATH-SEGMENTS";
  const std::string PATHS_PINS_COMMAND_WORKING_FOLDER = "KML-TOWN  --PATHS-PINS";
  const std::string JOIN_PATHS_COMMAND_WORKING_FOLDER = "KML-TOWN  --JOIN-PATHS";
  const std::string SPLIT_PATHS_COMMAND_WORKING_FOLDER = "KML-TOWN  --SPLIT-PATHS";
  const std::string TWINS_CHECK_COMMAND_WORKING_FOLDER = "KML-TOWN  --TWINS-CHECK";
  const std::string CLASSIFY_COMMAND_WORKING_FOLDER = "KML-TOWN  --CLASSIFY";
  const std::string FOLDER_BY_DATE_COMMAND_WORKING_FOLDER = "KML-TOWN --FOLDER-BY-DATE";
  const std::string FILTER_STRING_COMMAND_WORKING_FOLDER = "KML-TOWN  --FILTER-STRING";
}

namespace defs = definitions;

